name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Download dependencies
        run: nix develop -c composer update --no-interaction --no-progress

      - name: Run PHP CS Fixer
        run: nix develop -c php-cs-fixer fix --diff --dry-run
